CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentator_id BIGINT        NOT NULL,
    event_id       BIGINT        NOT NULL,
    text           VARCHAR(2000) NOT NULL,
    created        TIMESTAMP     NOT NULL,
    published      TIMESTAMP,
    status         VARCHAR(20)   NOT NULL CHECK (status IN ('NEW', 'PUBLISHED', 'REJECTED'))
);

