server:
  port: ${SERVER_PORT:8081}
  error:
    include-binding-errors: always

spring:
  application:
    name: ewm-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        serviceId: config-server
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5433/ewm-service
    url: jdbc:postgresql://ewm-db:5432/ewm-service
    username: ewm-service
    password: ewm-service
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10

logging:
  level:
    root: INFO

ewm:
  ewm-service:
    name: ewm-service
  # stats-server:
  #   url: http://localhost:9090
  stats-server:
    url: http://${STATS_SERVER_HOST:stats-server}:${STATS_SERVER_PORT:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:discovery-server}:${EUREKA_SERVER_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: "${spring.application.name}:${random.value}"

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
