spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: user_service_admin_users
          uri: lb://user-service
          order: -100
          predicates:
            - Path=/admin/users/**

        - id: category_service_admin
          uri: lb://category-service
          order: -90
          predicates:
            - Path=/admin/categories/**

        - id: category_service_public
          uri: lb://category-service
          order: -89
          predicates:
            - Path=/categories/**

        - id: compilation_service_admin
          uri: lb://compilation-service
          order: -80
          predicates:
            - Path=/admin/compilations/**

        - id: compilation_service_public
          uri: lb://compilation-service
          order: -79
          predicates:
            - Path=/compilations/**

        - id: request_service_event_requests
          uri: lb://request-service
          order: -70
          predicates:
            - Path=/users/*/events/*/requests/**

        - id: request_service_user_requests
          uri: lb://request-service
          order: -69
          predicates:
            - Path=/users/*/requests/**

        - id: comment_service_event_comments
          uri: lb://comment-service
          order: -60
          predicates:
            - Path=/events/*/comments/**

        - id: comment_service_admin
          uri: lb://comment-service
          order: -59
          predicates:
            - Path=/admin/comments/**

        - id: comment_service_user
          uri: lb://comment-service
          order: -58
          predicates:
            - Path=/users/comments/**

        - id: comment_service_root
          uri: lb://comment-service
          order: -57
          predicates:
            - Path=/comments/**

        - id: event_service_admin_events
          uri: lb://event-service
          order: -50
          predicates:
            - Path=/admin/events/**

        - id: event_service_private_events
          uri: lb://event-service
          order: -49
          predicates:
            - Path=/users/*/events/**

        - id: event_service_public_events
          uri: lb://event-service
          order: -48
          predicates:
            - Path=/events/**

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:discovery-server}:${EUREKA_SERVER_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
    ru.practicum.explore: DEBUG
