CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(255)      NOT NULL,
    description        VARCHAR(7000)     NOT NULL,
    annotation         VARCHAR(2000)     NOT NULL,
    lat                DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90.0 AND 90.0),
    lon                DOUBLE PRECISION NOT NULL CHECK (lon BETWEEN -180.0 AND 180.0),
    event_date         TIMESTAMP        NOT NULL,
    category_id        BIGINT           NOT NULL,
    initiator_id       BIGINT           NOT NULL,
    state              VARCHAR(20)      NOT NULL CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
    paid               BOOLEAN          NOT NULL,
    created_on         TIMESTAMP        NOT NULL,
    published_on       TIMESTAMP,
    participant_limit  INT              NOT NULL DEFAULT 0,
    request_moderation BOOLEAN          NOT NULL DEFAULT true
);

