spring:
  application:
    name: collector
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        serviceId: config-server
  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 0

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: collector

management:
  endpoints:
    web:
      exposure:
        include: health,info
